[workspace]
resolver = "2"

members = [
  "crates/cli",
  "crates/configuration",
  "crates/connectors/*",
  "crates/documentation/*",
  "crates/query-engine/*",
  "crates/tests/*",
]

[workspace.lints.clippy]
all = "warn"
