[workspace]
resolver = "2"

package.version = "0.1.0"
package.edition = "2021"
package.license = "Apache-2.0"

members = [
  "crates/connectors/ndc-postgres",
  "crates/query-engine/execution",
  "crates/query-engine/metadata",
  "crates/query-engine/sql",
  "crates/query-engine/translation",
  "crates/documentation/openapi",
  "crates/tests/other-db-tests",
  "crates/tests/tests-common"
]

# Temporary patch to get the build working. We shall remove this once a new
# version of ndc-spec is published, and ndc-sdk is updated accordingly.
# The "//" is to convince Cargo to accept this, due to
# https://github.com/rust-lang/cargo/issues/10756 .
[patch."https://github.com/hasura/ndc-spec.git"]
ndc-client = { git = "https://github.com/hasura//ndc-spec.git", rev = "3778605" }
ndc-test = { git = "https://github.com/hasura//ndc-spec.git", rev = "3778605" }
