[workspace]
resolver = "2"

package.version = "0.5.2"
package.edition = "2021"
package.license = "Apache-2.0"

members = [
    "crates/cli",
    "crates/configuration",
    "crates/connectors/*",
    "crates/documentation/*",
    "crates/query-engine/*",
    "crates/tests/*",
]

[workspace.lints.clippy]
all = "warn"

[workspace.dependencies]
ndc-client = { git = "https://github.com/hasura/ndc-spec.git", tag = "v0.1.1" }
ndc-sdk = { git = "https://github.com/hasura/ndc-sdk-rs.git", rev = "7b56fac3aba2bc6533d3163111377fd5fbeb3011" }
ndc-test = { git = "https://github.com/hasura/ndc-spec.git", tag = "v0.1.1" }
