[workspace]
resolver = "2"

package.version = "0.1.0"
package.edition = "2021"
package.license = "Apache-2.0"

members = [
  "crates/connectors/ndc-citus",
  "crates/connectors/ndc-cockroach",
  "crates/connectors/ndc-postgres",
  "crates/query-engine/execution",
  "crates/query-engine/metadata",
  "crates/query-engine/sql",
  "crates/query-engine/translation",
  "crates/documentation/openapi",
  "crates/tests/other-db-tests",
  "crates/tests/tests-common"
]
