[package]
name = "ndc-postgres-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ndc-postgres-configuration = { path = "../configuration" }

anyhow = "1.0.80"
clap = { version = "4.5.1", features = ["derive", "env"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.114", features = ["raw_value"] }
serde_yaml = "0.9.32"
thiserror = "1.0.57"
tokio = { version = "1.36.0", features = ["full"] }

[dev-dependencies]
insta = "1.35.1"
tempfile = "3.10.0"
