[package]
name = "ndc-postgres-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ndc-postgres-configuration = { path = "../configuration" }

anyhow = "1.0.86"
clap = { version = "4.5.4", features = ["derive", "env"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_yaml = "0.9.34"
thiserror = "1.0.61"
tokio = { version = "1.37.0", features = ["full"] }
serde_json = "1.0.117"

[build-dependencies]
build-data = "0.2.1"

[dev-dependencies]
insta = "1.39.0"
tempfile = "3.10.1"

[package.metadata.cargo-machete]
ignored = ["build_data"] # apparently cargo-machete doesn't find dependencies used by build scripts
