[package]
name = "ndc-postgres-cli"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
ndc-postgres-configuration = { path = "../configuration" }

anyhow = "1.0.79"
clap = { version = "4.5.1", features = ["derive"] }
serde_json = { version = "1.0.114", features = ["raw_value"] }
thiserror = "1.0.57"
tokio = { version = "1.36.0", features = ["full"] }

[dev-dependencies]
tempfile = "3.10.0"
