[package]
name = "ndc-postgres-cli"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
ndc-postgres-configuration = { path = "../configuration" }

anyhow = "1.0.79"
clap = { version = "4.4.8", features = ["derive"] }
serde_json = { version = "1.0.113", features = ["raw_value"] }
thiserror = "1.0.57"

[dev-dependencies]
tempfile = "3.10.0"
