[package]
name = "ndc-postgres-configuration"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
query-engine-metadata = { path = "../query-engine/metadata" }

anyhow = "1.0.81"
schemars = { version = "0.8.16", features = ["smol_str", "preserve_order"] }
serde = "1.0.197"
serde_json = { version = "1.0.114", features = ["raw_value"] }
sqlx = { version = "0.7.3", features = ["json", "postgres", "runtime-tokio-rustls"] }
thiserror = "1.0.57"
tokio = "1.36.0"
tracing = "0.1.40"
