[package]
name = "ndc-postgres-configuration"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
query-engine-metadata = { path = "../query-engine/metadata" }

ndc-sdk = { git = "https://github.com/hasura/ndc-hub.git", rev = "09edbd5" }

anyhow = "1.0.79"
serde = "1.0.196"
serde_json = { version = "1.0.113", features = ["raw_value"] }
sqlx = { version = "0.7.3", features = [ "json", "postgres", "runtime-tokio-rustls" ] }
tracing = "0.1.40"
