[package]
name = "ndc-postgres-configuration"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
query-engine-metadata = { path = "../query-engine/metadata" }

anyhow = "1.0.82"
schemars = { version = "0.8.17", features = ["smol_str", "preserve_order"] }
serde = "1.0.200"
serde_json = { version = "1.0.116", features = ["raw_value"] }
sqlx = { version = "0.7.4", features = ["json", "postgres", "runtime-tokio-rustls"] }
thiserror = "1.0.59"
tokio = "1.37.0"
tracing = "0.1.40"
