{
 "title": "Postgres NDC",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Query time - query execution time - connection acquisition time",
   "type": "gauge",
   "description": "This is only the time inside `ndc-postgres` rather than including any time spent in ndc-hub functions / axum router.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ndc_postgres_query_total_time_sum - ndc_postgres_query_execution_time_sum - ndc_postgres_connection_acquisition_wait_time_sum) / ndc_postgres_query_total_time_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query time - query execution time",
   "type": "gauge",
   "description": "This is only the time inside `ndc-postgres` rather than including any time spent in ndc-hub functions / axum router.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ndc_postgres_query_total_time_sum - ndc_postgres_query_execution_time_sum) / ndc_postgres_query_total_time_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total connection acquisition wait time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(ndc_postgres_connection_acquisition_wait_time_sum[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total query execution time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(ndc_postgres_query_execution_time_sum[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection acquisition wait time",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ndc_postgres_connection_acquisition_wait_time_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query execution time",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ndc_postgres_query_execution_time_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rate(ndc_postgres_query_total[1m])"
    },
    { "expr": "ndc_postgres_explain_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connection pool size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    { "expr": "ndc_postgres_pool_size", "legendFormat": "__auto" },
    {
     "expr": "ndc_postgres_pool_max_connections",
     "legendFormat": "__auto"
    },
    {
     "expr": "ndc_postgres_pool_min_connections",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}