# This is extended configuration for the `cargo nextest` test runner.
# It will not be applied when using `cargo test`.

[profile.default]
# Mark any test that takes longer than 15 seconds as "slow",
# and terminate and fail the test after 60 seconds.
slow-timeout = { period = "15s", terminate-after = 4 }
