[package]
name = "query-engine-metadata"
version.workspace = true
edition.workspace = true

[dependencies]
enum-iterator = "1.4.1"
schemars = { version = "0.8.15", features = ["smol_str"] }
serde = { version = "1.0.188", features = ["derive"] }
