[package]
name = "query-engine-metadata"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ndc-models = { workspace = true }
smol_str = { workspace = true }
