[package]
name = "openapi-generator"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

default-run = "openapi-generator"

[lib]
name = "openapi_generator"
path = "src/lib.rs"

[[bin]]
name = "openapi-generator"
path = "src/main.rs"

[dependencies]
ndc-postgres = { path = "../../connectors/ndc-postgres" }
schemars = { version = "0.8.16", features = ["smol_str", "preserve_order"] }
serde_json = { version = "1.0.112", features = ["raw_value"] }

[dev-dependencies]
insta = { version = "1.34.0", features = ["json"] }
