[package]
name = "openapi-generator"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
insta = { version = "1.34.0", features = ["json"] }
ndc-postgres = { path = "../../connectors/ndc-postgres" }
schemars = { version = "0.8.16", features = ["smol_str", "preserve_order"] }
serde_json = { version = "1.0.109", features = ["raw_value"] }
