[package]
name = "openapi-generator"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lints]
workspace = true

[lib]
name = "openapi_generator"
path = "src/lib.rs"

[[bin]]
name = "openapi-generator"
path = "src/main.rs"

[dependencies]
ndc-postgres-configuration = { path = "../../configuration" }
schemars = { version = "0.8.16", features = ["smol_str", "preserve_order"] }
serde_json = { version = "1.0.114", features = ["raw_value"] }
