[package]
name = "openapi-generator"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
insta = { version = "1.34.0", features = ["json"] }
ndc-postgres = { path = "../../connectors/ndc-postgres" }
schemars = { version = "0.8.16", features = ["smol_str", "preserve_order"] }
serde_json = { version = "1.0.108", features = ["raw_value"] }
