[package]
name = "query-engine-sql"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
schemars = { version = "0.8.19", features = ["smol_str", "preserve_order"] }
serde = "1.0.201"
serde_json = "1.0.117"
