[package]
name = "query-engine-sql"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
schemars = { version = "0.8.16", features = ["smol_str", "preserve_order"] }
serde = "1.0.193"
itertools = "^0.12.0"
serde_json = "1.0.108"
itertools = "^0.12.0"
