on:
  workflow_dispatch:
    inputs:
      new_version:
        description: "What we want the new version to be"
        required: true

name: Bump version

jobs:
  bump_version_pr:
    name: Create version bump PR
    runs-on: ubuntu-latest
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - uses: actions/checkout@v4

      - name: Install `just`
        uses: extractions/setup-just@v2

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build" # share the cache across jobs
          save-if: false

      - run: ./scripts/new-version.sh ${{ github.event.inputs.new_version }}

      - uses: peter-evans/create-pull-request@v6
        with:
          title: Bump version to ${{ github.event.inputs.new_version }}
          body: This bumps the version in `Cargo.toml` and updates `changelog.md`.
          team-reviewers: hasura/api-pg
