on: [push]

name: cargo audit

jobs:
  cargo_audit:
    name: cargo audit
    runs-on: ubuntu-latest
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: dorny/paths-filter@9d7afb8d214ad99e78fbd4247752c4caed2b6e4c # v4
        id: changes
        with:
          filters: |
            cargo:
              - "**/Cargo.toml"
              - "**/Cargo.lock"

      - if: steps.changes.outputs.cargo == 'true'
        name: Install `just`
        uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3

      - if: steps.changes.outputs.cargo == 'true'
        name: install tools
        run: |
          rustup show
          cargo install cargo-audit

      - if: steps.changes.outputs.cargo == 'true'
        uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae # v2
        with:
          shared-key: "build" # share the cache across jobs

      - if: steps.changes.outputs.cargo == 'true'
        run: just audit
