name: find unused dependencies

on:
  push:

jobs:
  cargo-machete:
    name: find unused dependencies with cargo machete
    runs-on: ubuntu-latest
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      RUSTFLAGS: "-D warnings" # fail on warnings
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: install tools
        run: |
          rustup show
          cargo install cargo-machete@0.7.0 # Need Rust 2024 edition before we can upgrade this

      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          shared-key: "build" # share the cache across jobs
          save-if: false

      - name: find unused dependencies
        run: |
          cargo machete --with-metadata
