on: [push]

name: Postgres NDC build

jobs:
  build:
    name: Build Postgres NDC
    runs-on: ubuntu-latest
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      RUSTFLAGS: "-D warnings" # fail on warnings
    steps:
      - uses: actions/checkout@v4

      - name: install protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "24.3"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: install tools
        run: |
          rustup show

      - uses: Swatinem/rust-cache@v2

      - name: build crates
        run: |
          cargo build --release --all-features

      # Sadly, `cargo build --locked` isn't enough to check that the lockfile
      # is up to date, as it will happily run even if there are extra entries in
      # there.
      #
      # It does, however, make sure that the file is not updated, which is quite
      # unhelpful.
      - name: ensure lockfile hasn't changed
        run: |
          if [[ -n "$(git status --porcelain Cargo.lock)" ]]; then
            echo 'The Cargo.lock file was changed!'
            git diff Cargo.lock
            exit 1
          fi

      - name: lint
        run: |
          cargo clippy --release -- --deny=clippy::all
