on: [push]

name: cargo audit

jobs:
  cargo_audit:
    name: cargo audit
    runs-on: ubuntu-latest
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: changes
        with:
          filters: |
            cargo:
              - "**/Cargo.toml"
              - "**/Cargo.lock"

      - if: steps.changes.outputs.cargo == 'true'
        name: Install `just`
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0

      - if: steps.changes.outputs.cargo == 'true'
        name: install tools
        run: |
          rustup show
          cargo install cargo-audit

      - if: steps.changes.outputs.cargo == 'true'
        uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae # v2
        with:
          shared-key: "build" # share the cache across jobs

      - if: steps.changes.outputs.cargo == 'true'
        run: just audit
