name: Postgres NDC Configuration Server
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-and-test:
    name: Build and test docker build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker build
        run: docker build --file ConfigServer.Dockerfile -t ndc-postgres-config-server:1 .

      - name: Run docker build
        run: docker run -d -p 9100:9100 ndc-postgres-config-server:1

      - name: Test
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: "http://localhost:9100/"
          responseCode: "200"
          timeout: 2000
          interval: 1000
