on:
  push:
    branches:
      # - main

name: Create version tag

jobs:
  tag_main_commit:
    name: Check for tag-triggering commit to `main`
    runs-on: ubuntu-latest
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"

    steps:
      - name: Is this a commit we need to tag?
        id: tag_check
        run: |
          is_tagged_commit="${{ github.event.head_commit.message }}" \
            | grep "^🚀 Bump version to \d\+\.\d\+\.\d\+" | wc -l
          echo "is_tagged_commit=$is_tagged_commit" >> $GITHUB_OUTPUT

      - name: Debug again
        env:
          IS_TAGGED_COMMIT: ${{ steps.tag_check.outputs.is_tagged_commit }}
        run: echo "TAGGED? $IS_TAGGED_COMMIT"
